baseURL: https://www.jakobthe.dev/
title: Jakob Pennington 
theme: "PaperMod"
languageCode: en-us

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-29MNLJYDQX

disqusShortname: JakobTheDev

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Jakob Pennington
  description: "Jakob Pennington's blog"
  keywords: [Blog, AppSec]
  author: Jakob Pennington
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2 January 2006"
  defaultTheme: dark
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "images/favicon.ico"
    favicon16x16: "images/favicon-16x16.png"
    favicon32x32: "images/favicon-32x32.png"
    apple_touch_icon: "images/apple-touch-icon.png"
    safari_pinned_tab: "images/apple-touch-icon.png"

  label:
    text: "Home"
    # icon: /images/favicon-32x32.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true
    title: Jakob Pennington
    subtitle: "JakobTheDev"
    imageUrl: "images/profile.png"
    imageWidth: 240
    imageHeight: 240
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      # - name: Tags
      #   url: tags

  socialIcons:
    - name: mastodon
      url: "https://infosec.exchange/@JakobPennington"
    - name: twitter
      url: "https://twitter.com/@JakobTheDev"
    - name: github
      url: "https://github.com/JakobTheDev"
    - name: linkedin
      url: "https://www.linkedin.com/in/jakobpennington/"

  analytics:
    google:
      SiteVerificationTag: "G-29MNLJYDQX"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/JakobTheDev/website/content"
    Text: "Suggest Changes"
    appendFilePath: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About Me
      url: /posts/about-me
      weight: 10
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai